#!/usr/bin/env bash
set -o errexit
set -o pipefail


# Cleanup libvirt VMs / networks
delete_libvirt_vms
clear_libvirt_networks

if [[ -d $WORKSPACE/ceph_vstart ]]; then
    # Stop vstart cluster
    pushd $WORKSPACE/ceph/build
    ../src/stop.sh
    popd
fi

# Cleanup remaining files / directories
sudo rm -rf \
    $WORKSPACE/ceph $WORKSPACE/ceph_vstart $WORKSPACE/ceph.zip \
    $WORKSPACE/libvirt_windows_vm
