#!/usr/bin/env bash
set -o errexit
set -o pipefail

export VSTART_DIR="$WORKSPACE/ceph_vstart"
export VSTART_MEMSTORE_BYTES="5368709120"  # 5GB

#
# Build Ceph vstart
#
cd $WORKSPACE/ceph
./install-deps.sh
./do_cmake.sh \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_RADOSGW=OFF \
    -DWITH_MGR_DASHBOARD_FRONTEND=OFF \
    -DWITH_TESTS=OFF
cd ./build
ninja vstart

#
# Run Ceph vstart
#
rm -rf $VSTART_DIR
mkdir -p $VSTART_DIR/out
../src/stop.sh

OSD_POOL_DEFAULT_SIZE=1 VSTART_DEST=$VSTART_DIR ../src/vstart.sh \
    -n --memstore -o "memstore_device_bytes=$VSTART_MEMSTORE_BYTES" \
    -i "192.168.122.1" \
    2>&1 | tee $VSTART_DIR/vstart.log

export CEPH_CONF="$VSTART_DIR/ceph.conf"
export CEPH_KEYRING="$VSTART_DIR/keyring"
export CEPH_WINDOWS_CONF="$VSTART_DIR/ceph-windows.conf"

MON_HOST=$(cat $CEPH_CONF | grep -o "mon host \=.*")

cat > $CEPH_WINDOWS_CONF << EOF
[client]
    keyring = C:/ProgramData/ceph/keyring
    admin socket = C:/ProgramData/ceph/out/$name.$pid.asok
    client_mount_uid = 1000
    client_mount_gid = 1000
    client_permissions = true
[global]
    log to stderr = true
    run dir = C:/ProgramData/ceph/out
    crash dir = C:/ProgramData/ceph/out
    $MON_HOST
EOF

./bin/ceph osd pool create rbd

./bin/ceph osd pool set cephfs.a.data size 1 --yes-i-really-mean-it
./bin/ceph osd pool set cephfs.a.meta size 1 --yes-i-really-mean-it
./bin/ceph osd pool set rbd size 1 --yes-i-really-mean-it

./bin/ceph tell mon.\* config set debug_mon 0
./bin/ceph tell mon.\* config set debug_ms 0
