- job:
    name: ceph-windows-image-build
    description: 'Builds the Ceph Windows VM image used in the CI.'
    node: amd64 && focal && libvirt
    project-type: freestyle
    defaults: global
    concurrent: false
    display-name: 'ceph-windows-image-build'
    properties:
      - build-discarder:
          days-to-keep: 30
          num-to-keep: 30
          artifact-days-to-keep: 30
          artifact-num-to-keep: 30

    parameters:
      - string:
          name: WINDOWS_SERVER_2019_ISO_URL
          description: "The Windows Server 2019 ISO URL."
          default: https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso

      - string:
          name: WINDOWS_SERVER_2019_ISO_CHECKSUM
          description: "The Windows Server 2019 ISO checksum. The accepted format is 'CHECKSUM_ALGORITHM:CHECKSUM' (e.g. 'md5:70fec2cb1d6759108820130c2b5496da')."
          default: sha256:549bca46c055157291be6c22a3aaaed8330e78ef4382c99ee82c896426a1cee1

      - string:
          name: VIRTIO_WIN_ISO_URL
          description: "The virtio-win guest tools ISO URL."
          default: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          branches:
            - master

    builders:
      - shell: "${WORKSPACE}/ceph-windows-image-build/build/build"

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                - ABORTED
              build-steps:
                - shell: "${WORKSPACE}/ceph-windows-image-build/build/cleanup"
